### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by eddiejaoude** [phansible/phansible#228]
Would be great to have docker support too.

eg.

```yaml
# ansible/roles/docker/tasks/main.yml

- name: install pip
  shell: curl https://bootstrap.pypa.io/get-pip.py | python -

- name: install docker py
  shell: pip install docker-py

- name: install docker
  shell: curl -sSL https://get.docker.com/ | sh && sudo usermod -aG docker vagrant

- include: elasticsearch.yml
```

```yaml
# ansible/roles/docker/tasks/elasticsearch.yml

- name: elasticsearch container
  docker:
    name: elasticsearch
    image: elasticsearch
    state: started
    expose:
      - 9200
```
