### ISSUE TITLE
xdebug settings not applied

### ISSUE THREAD

**Issue by eddiejaoude** [phansible/phansible#229]
the **xdebug/default/main.yml** has the following in it by default:

```yaml
---
xdebug:
    settings: []
```

So, I updated it to...

``` yaml
---
xdebug:
    settings:
        - xdebug.remote_enable=1
        - xdebug.remote_host=192.168.33.1
        - xdebug.remote_port=9000
```

But nothing is applied to `/etc/php5/mods-available/xdebug.ini`

Am I missing something?
