### ISSUE TITLE
Npm support would be useful

### ISSUE THREAD

**Issue by eddiejaoude** [phansible/phansible#230]
Similar to the Docker idea/proposal, Ansible supports **npm**, thus would be great if Phansible exposed this functionality.

eg.
```yaml
- name: install npm
  apt:  pkg=npm state=present

- name: install global node packages
  npm: name={{item}} global=yes
  with_items:
    - bower
    - grunt-cli
    - express
    - socket.io
```
