### ISSUE TITLE
Contribution for CentOS support

### ISSUE THREAD

**Issue by debo** [phansible/phansible#235]
Hey @naxhh @erikaheidi pointed me in your direction. I'm willing to step-up on this one. I seen that where was a previous issue open later closed with no progress. Are you ok with me to go on with this? How would you prefer me to proceed?

**Comment by naxhh** [comment]
As said in #26 we are open to CentOS support if the community needs it.

My requirements list would be:

- No major changes in the code (php code)
- Easy to maintain, responsibility well defined between OS in the playbooks.
- Clear strategy for package naming (httpd vs apache2, specific configs, etc)

Do you have any idea on how you would approach it? Will be nice to be in the loop :)

**Comment by MarcoDeBortoli** [comment]
I think the community will surely benefit from this, pretty much all the companies I worked for uses RHEL based setups in production and adopt CentOS as development environment seems the right choice. Also I think it surely won't hurt to much to give more flexibility to the Phansible users, the more the merrier they say right?

In regards to your requests; I can't promise anything about the code yet because I didn't have much chance to dig into it but of course I'll try to keep that in mind and not be too disruptive or if needed, I will try to provide slow incremental changes. About playbooks Ansible offers us all the flexibility we need even preventing role duplications; roles can be self contained and deal with the different OS in isolation. The strategy about packages naming convention is, well, a naming convention indeed so we are free to decide what better fits our needs.

I currently started amending the config file for the boxes lists and I also created and uploaded the needed boxes on ![vagrant cloud](https://atlas.hashicorp.com/MarcoDeBortoli) and I will shortly start looking in the varius roles do abstract them and ensure they are cross platform.

I'll definitely keep you in the loop.

**Comment by fabiorphp** [comment]
Hi Guys!

Well, for this approach, it's if necessary to duplicate some tasks for the 2 OS's and create a conditional when include the task for specific OS.

In the PHP code it's not necessary to make any changes, because it's not responsible for it.

**Comment by MarcoDeBortoli** [comment]
That's exactly what I was expecting indeed. Ansible should be able to manage most of this. However I've been told that various things are "hardcoded" as twig templates where possibly the problem could be. We will see how I get along with it and if I have questions I'll shout.

**Comment by fabiorphp** [comment]
Go Ahead!
I think that you should start with ansible roles, after that, you should change the PHP code to put OS information.

**Comment by naxhh** [comment]
Thanks @MarcoDeBortoli!

The points where to check if we are in the same page in this regards. All seems fine. So go ahead :)

**Comment by MarcoDeBortoli** [comment]
@naxhh and @fabiorphp thanks for the trust and the opportunity. Cheers.

**Comment by marcodebortoli** [comment]
@naxhh @fabiorphp what's the meaning/purpose of the `install: 1` bit in the vars file?

```yaml
server:
    install: '1'
    timezone: Europe/London
    locale: en_GB.UTF-8
vagrant_local:
    install: '1'
    vm: { base_box: precise32, hostname: default, ip: 172.16.0.2, memory: '512', sharedfolder: ./, enableWindows: '1', useVagrantCloud: '1', syncType: nfs }
apache:
    install: '1'
    docroot: /vagrant
    servername: phansible.dev
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt]
xdebug:
    install: '1'
composer:
    install: '1'
```
