### ISSUE TITLE
PHP PECL packages not installed because of naming mis-match

### ISSUE THREAD

**Issue by philbates35** [phansible/phansible#251]
When you generate a fresh .zip from the website now, any PHP PECL packages that are specified aren't installed. The reason is that in `ansible/vars/all.yml` the PECL variable is defined as `php.peclpackages`, but in `ansible/roles/php/tasks/pecl.yml` it is expecting the variable to be called `php.pecl_packages`. As `php.pecl_packages` is never defined, PECL packages are never installed.

Generated `ansible/vars/all.yml`:
```yml
...
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-mcrypt, php5-curl, php5-gd, php5-mysql]
    peclpackages: [mailparse]
...
```

Generated `ansible/roles/php/tasks/pecl.yml`:
```yml
- name: Install
  apt: pkg="php5-dev" state=present
  when: php.pecl_packages is defined

- name: Install Package
  shell: echo "\n\n\n\n\n\n\n\n\n" | pecl install {{ item }}
  register: pecl_result
  changed_when: "'already installed' not in pecl_result.stdout"
  failed_when: "pecl_result.stderr or ('ERROR' in pecl_result.stdout)"
  with_items: php.pecl_packages
  when: php.pecl_packages is defined

- name: Create extension .ini file
  template: >
    src="extension.tpl"
    dest="/etc/php5/mods-available/{{ item }}.ini"
    owner="root"
    group="root"
    mode=0644
  with_items: php.pecl_packages
  when: php.pecl_packages is defined

- name: Enable extension
  shell: php5enmod {{ item }}
  with_items: php.pecl_packages
  when: php.pecl_packages is defined
```
