### ISSUE TITLE
Add post_tasks for open in browser in playbook

### ISSUE THREAD

**Issue by AaronTraas** [phansible/phansible#96]
I always add the following to my provisioning playbook:

``` yml
  post_tasks:
    - name: open URL
      sudo: no
      local_action: shell open {{ base_url }}
      ignore_errors: yes
```

It opens the site in a browser. It necessitates the creation of the `base_url` variable in the inventory file, which I always do for other reasons as well.
